import { Property, Host, Review, ChatThread, UserProfile, Notification, Booking, PurchaseOrder } from './types';

export const currencies = [
  { code: 'GBP', symbol: '£', label: 'British Pound (GBP)', rate: 1.0 },
  { code: 'USD', symbol: '$', label: 'US Dollar (USD)', rate: 1.30 },
  { code: 'EUR', symbol: '€', label: 'Euro (EUR)', rate: 1.18 },
  { code: 'JPY', symbol: '¥', label: 'Japanese Yen (JPY)', rate: 198.50 },
  { code: 'AUD', symbol: 'A$', label: 'Australian Dollar (AUD)', rate: 1.95 },
];

export const languages = [
  { code: 'en', name: 'English (UK)', flag: '🇬🇧' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
];

export const PROPERTY_TYPES = [
  { id: 'villas', name: 'Villas', icon: 'Home', count: 124 },
  { id: 'cabins', name: 'Cabins', icon: 'Trees', count: 85 },
  { id: 'apartments', name: 'City Apartments', icon: 'Building', count: 240 },
  { id: 'tiny-homes', name: 'Tiny Homes', icon: 'Compass', count: 42 },
  { id: 'castles', name: 'Castles', icon: 'Crown', count: 18 },
  { id: 'beachfront', name: 'Beachfront Stays', icon: 'Palmtree', count: 110 },
  { id: 'mountain', name: 'Mountain Retreats', icon: 'Mountain', count: 95 },
];

export const TRENDING_DESTINATIONS = [
  {
    id: 'dest-1',
    city: 'Cotswolds',
    country: 'United Kingdom',
    image: 'https://images.unsplash.com/photo-1543872084-c7bd3822856f?q=80&w=800&auto=format&fit=crop',
    propertiesCount: 45,
    tagline: 'Quaint stone villages & golden valleys',
  },
  {
    id: 'dest-2',
    city: 'Amalfi Coast',
    country: 'Italy',
    image: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?q=80&w=800&auto=format&fit=crop',
    propertiesCount: 78,
    tagline: 'Dramatic cliffs & pastel-colored villas',
  },
  {
    id: 'dest-3',
    city: 'Kyoto',
    country: 'Japan',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    propertiesCount: 62,
    tagline: 'Bamboo forests & historic temples',
  },
  {
    id: 'dest-4',
    city: 'Reykjavik',
    country: 'Iceland',
    image: 'https://images.unsplash.com/photo-1504829857797-ddff28127792?q=80&w=800&auto=format&fit=crop',
    propertiesCount: 34,
    tagline: 'Northern lights & geothermal springs',
  },
  {
    id: 'dest-5',
    city: 'Santorini',
    country: 'Greece',
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=800&auto=format&fit=crop',
    propertiesCount: 89,
    tagline: 'Iconic blue domes & sunset horizons',
  },
];

export const BLOG_POSTS = [
  {
    id: 'blog-1',
    title: '10 Hidden Coastal Retreats in the UK You Need to Visit',
    excerpt: 'From isolated cliffside cabins in Cornwall to remote beachside cottages in Scotland, discover the UK’s best-kept secrets.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
    date: 'Jun 28, 2026',
    author: 'Eleanor Vance',
    readTime: '5 min read',
    content: [
      'The British coastline is a dramatic, wind-swept canvas of rugged cliffs, golden sands, and historic harbors. While popular destinations like St. Ives and Brighton attract thousands of sun-seekers every summer, there exists a quieter, more poetic world of hidden sanctuaries. These remote escapes offer travelers a chance to slow down, listen to the rhythmic crash of Atlantic waves, and experience the wild beauty of the sea in absolute solitude.',
      'In Cornwall, tucked away down narrow, single-track lanes lined with wild gorse, you’ll find off-grid timber cabins resting on the high cliffs. Built from local larch and reclaimed driftwood, these tiny sanctuaries feature floor-to-ceiling glass walls that frame panoramic sea views. Here, mornings begin with the scent of salty air and the sight of gulls gliding on thermal currents. There are no televisions or traffic noises—only the crackle of a wood-burning stove and the distant, deep hum of the ocean.',
      'Further north, along the dramatic coastlines of the Scottish Highlands and the Isle of Skye, stone-built cottages stand strong against the elements. Originally constructed as crofters’ shelters in the 19th century, these buildings have been beautifully reimagined by modern architects. Inside, ancient granite walls meet warm oak floors, minimalist Scandinavian furniture, and deep copper soaking tubs that look out over silent, mist-shrouded lochs.',
      'Whether you’re seeking a creative retreat to write your next novel, a romantic getaway with wood-fired hot tubs under star-filled skies, or simply a weekend of digital detachment, these ten verified coastal sanctuaries promise an unforgettable encounter with the wild edge of Britain.'
    ]
  },
  {
    id: 'blog-2',
    title: 'Designing the Ultimate Slow-Living Remote Workspace',
    excerpt: 'Digital nomads share their tips on finding properties that balance blazing fast fiber internet with natural, peaceful surroundings.',
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=800&auto=format&fit=crop',
    date: 'May 14, 2026',
    author: 'James Sterling',
    readTime: '8 min read',
    content: [
      'The boundary between work and life has dissolved, giving rise to a new generation of design-conscious professionals who prioritize wellness and inspiration alongside productivity. Slow living is not about doing things slowly; it is about finding the right pace to appreciate your environment, foster deep focus, and cultivate genuine creativity.',
      'A true slow-living remote workspace is built on three pillars: abundant natural light, acoustic tranquility, and an immediate connection to nature. Traditional sterile offices or cluttered hotel desks fail to inspire the mind. Instead, we look for properties that incorporate biophilic design—using raw timbers, organic linen textiles, and potted ferns to bring the soothing elements of the outdoors inside.',
      'Our digital nomad community emphasizes that technology should be a silent, reliable partner rather than a constant distraction. High-speed fiber-optic internet and multiple power stations are essential prerequisites for any modern workspace, but they must be integrated gracefully. Cable management, flush-mounted ports, and height-adjustable oak desks ensure that the physical workspace remains clean, organized, and conducive to deep focus sessions.',
      'To design your own slow-living workspace while traveling, choose stays with dedicated workspaces situated near windows that look out onto gardens, forests, or mountain ridges. Take structured offline breaks every two hours: walk barefoot on the lawn, brew a cup of ceremonial-grade matcha, or simply sit on the deck and watch the wind move through the trees. By aligning your workflow with the natural rhythms of your sanctuary, you will discover a profound, highly sustainable sense of focus.'
    ]
  },
  {
    id: 'blog-3',
    title: 'Villas of Amalfi: Architectural Wonders on Cliff Edges',
    excerpt: 'A deep-dive review of historical coastal architecture and the gorgeous, centuries-old estates you can actually book today.',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?q=80&w=800&auto=format&fit=crop',
    date: 'Apr 22, 2026',
    author: 'Marcello Rossi',
    readTime: '12 min read',
    content: [
      'The Amalfi Coast is a vertical marvel where gravity-defying architecture clings to sheer limestone cliffs. For centuries, artists, poets, and aristocratic families have been drawn to this stretch of Italian coastline, where the Tyrrhenian Sea meets terraced lemon groves and pastel-colored stone estates that cascade down to hidden coves.',
      'At the heart of Amalfi’s architectural identity are the ancient cliffside villas, many of which date back to the Roman Empire and the Middle Ages. These estates were originally constructed as fortified lookouts or summer palaces for noble merchants. They are characterized by sweeping groin vaults, high arched windows, limestone plaster walls, and hand-painted majolica ceramic tiles from the nearby town of Vietri sul Mare.',
      'Restoring these historical wonders is a monumental task that requires a delicate balance between preserving ancient heritage and introducing modern luxury. Architects must work closely with regional preservation boards to ensure that structural modifications respect the original stonework. Today, the finest Amalfi villas blend antique frescoed ceilings and stone-carved fireplaces with state-of-the-art climate control, infinity-edge pools that melt into the ocean horizon, and professional chef-grade kitchens.',
      'Booking one of these private sanctuaries is more than just securing a place to sleep; it is an immersive step back in time. To spend an evening watching the sunset paint the cliffs of Positano in shades of apricot and lavender from a private, terracotta-tiled terrace is to experience the true essence of Italian luxury and the architectural mastery of a bygone era.'
    ]
  },
];

export const TESTIMONIALS = [
  {
    id: 'test-1',
    name: 'Sarah Jenkins',
    location: 'London, UK',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&auto=format&fit=crop',
    rating: 5,
    comment: 'ProStates completely redefined how our family travels. The properties are exactly as described, checked to a standard of excellence that other platforms simply do not match.',
  },
  {
    id: 'test-2',
    name: 'Hiroshi Sato',
    location: 'Tokyo, Japan',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop',
    rating: 5,
    comment: 'The booking experience was flawless, and the multi-currency conversions were accurate and fair. The host in Cornwall went out of his way to welcome us. Incredible service.',
  },
  {
    id: 'test-3',
    name: 'Emily de Ridder',
    location: 'Amsterdam, Netherlands',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop',
    rating: 5,
    comment: 'As a digital nomad, finding stable high-speed Wi-Fi and ergonomic workspaces is paramount. ProStates filters actually worked, saving me hours of searching.',
  },
];

export const FAQS = [
  {
    question: 'How are properties verified on ProStates?',
    answer: 'Every listing on ProStates goes through a comprehensive 50-point physical or video check by our regional curators. We verify physical address, essential amenities (like high-speed Wi-Fi and HVAC), safety equipment, cleanliness, and the host’s identities.',
  },
  {
    question: 'What is the cancellation policy?',
    answer: 'ProStates offers three standardized cancellation tiers: Flex (free cancellation up to 48 hours before check-in), Balanced (free cancellation up to 7 days before check-in), and Secure (50% refund up to 14 days before check-in). This policy is clearly displayed on each stay page.',
  },
  {
    question: 'Can I pay in my local currency?',
    answer: 'Yes! ProStates supports instant localized billing in over 30 currencies. We use live interbank market exchange rates updated hourly, without hidden loading fees, so you pay exactly what you see.',
  },
  {
    question: 'How do I become a ProStates Host?',
    answer: 'Click "Become a Host" in the header to launch our intuitive property onboarding flow. Once you fill in your property details and upload professional photography, our curation team will schedule a verification session to live-approve your listing.',
  },
];

export const MOCK_HOSTS: Host[] = [
  {
    id: 'host-1',
    name: 'Lord Arthur Pendelton',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&auto=format&fit=crop',
    rating: 4.95,
    reviewsCount: 342,
    isSuperHost: true,
    joinedDate: 'March 2021',
    responseRate: 100,
    responseTime: 'Within an hour',
  },
  {
    id: 'host-2',
    name: 'Clara & Giovanni',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=150&auto=format&fit=crop',
    rating: 4.89,
    reviewsCount: 184,
    isSuperHost: true,
    joinedDate: 'September 2023',
    responseRate: 98,
    responseTime: 'Within a few hours',
  },
  {
    id: 'host-3',
    name: 'Kenji Tanaka',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=150&auto=format&fit=crop',
    rating: 4.98,
    reviewsCount: 96,
    isSuperHost: true,
    joinedDate: 'January 2024',
    responseRate: 100,
    responseTime: 'Within a few minutes',
  },
  {
    id: 'host-4',
    name: 'Sven Lindqvist',
    avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=150&auto=format&fit=crop',
    rating: 4.82,
    reviewsCount: 74,
    isSuperHost: false,
    joinedDate: 'June 2024',
    responseRate: 95,
    responseTime: 'Within an hour',
  },
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    title: 'The Stone Manor Estate & Private Gardens',
    description: 'Immerse yourself in history at this iconic Grade-II listed stone manor house nestled in the heart of the Cotswolds. The property features beautifully manicured English gardens, exposed medieval timber beams, modern bespoke country-style kitchens, a heated indoor swimming pool, and an exquisite library room with a fireplace. Perfect for large family assemblies or multi-family holidays searching for tranquility and timeless British charm.',
    country: 'United Kingdom',
    city: 'Cotswolds',
    countryCode: 'GB',
    rating: 4.94,
    reviewsCount: 142,
    pricePerNight: 450,
    currency: 'GBP',
    guestsMax: 10,
    bedrooms: 5,
    bathrooms: 4.5,
    amenities: ['Wi-Fi', 'Parking', 'Fireplace', 'Heated Pool', 'Library', 'Kitchen', 'Washing Machine', 'Pet Friendly', 'Workspace'],
    images: [
      'https://images.unsplash.com/photo-1543872084-c7bd3822856f?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=1200&auto=format&fit=crop'
    ],
    type: 'Castle',
    category: 'luxury',
    isSuperHost: true,
    isVerified: true,
    isInstantBook: true,
    host: MOCK_HOSTS[0],
    latitude: 42,
    longitude: 32,
    featured: true,
    transactionMode: 'rental',
  },
  {
    id: 'prop-2',
    title: 'Villa Bel-Air Cliffside & Infiniti Pool',
    description: 'Hovering spectacularly above the shimmering turquoise Mediterranean Sea, Villa Bel-Air offers absolute privacy and unparalleled panorama of the Amalfi Coast. Features include floor-to-ceiling retractable glass doors, an private infinity pool reflecting the Italian horizon, sweeping multi-level stone terraces, custom Italian designer furnishings, and direct private elevator access to a hidden beach inlet.',
    country: 'Italy',
    city: 'Positano',
    countryCode: 'IT',
    rating: 4.98,
    reviewsCount: 89,
    pricePerNight: 620,
    currency: 'EUR',
    guestsMax: 6,
    bedrooms: 3,
    bathrooms: 3.5,
    amenities: ['Wi-Fi', 'Air Conditioning', 'Infinity Pool', 'Elevator', 'Kitchen', 'Beach Access', 'Parking', 'Terrace'],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=1200&auto=format&fit=crop',
    ],
    type: 'Villa',
    category: 'beach',
    isSuperHost: true,
    isVerified: true,
    isInstantBook: true,
    host: MOCK_HOSTS[1],
    latitude: 58,
    longitude: 65,
    featured: true,
    transactionMode: 'buy',
    salePrice: 1250000,
  },
  {
    id: 'prop-3',
    title: 'Kyoto Hanare Traditional Wooden Machiya',
    description: 'An elegantly restored 120-year-old traditional machiya townhouse in Kyoto\'s historic district. Merging timeless Japanese carpentry with contemporary architectural comforts, it includes private tatami tea rooms, a central stone zen garden, an outdoor Hinoki wood soaking tub (ofuro), sliding washi doors, and premium floor heating. Walk to local temples and bamboo groves.',
    country: 'Japan',
    city: 'Kyoto',
    countryCode: 'JP',
    rating: 4.99,
    reviewsCount: 76,
    pricePerNight: 280,
    currency: 'JPY',
    guestsMax: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ['Wi-Fi', 'Hinoki Soaking Tub', 'Zen Garden', 'Kitchen', 'Heating', 'Workspace', 'Tea Room'],
    images: [
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=1200&auto=format&fit=crop',
    ],
    type: 'Tiny Home',
    category: 'city',
    isSuperHost: true,
    isVerified: true,
    isInstantBook: false,
    host: MOCK_HOSTS[2],
    latitude: 75,
    longitude: 48,
    featured: true,
    transactionMode: 'installment',
    salePrice: 850000,
    installmentPrice: 3800,
    installmentsDurationMonths: 240,
  },
  {
    id: 'prop-4',
    title: 'Aurora Geothermal Glass Cabin',
    description: 'Watch the dance of the spectacular Northern Lights directly from your bed. Nestled within an expansive private Icelandic lava field, this architecturally unique glass-roof cabin utilizes green geothermal heat. Includes a private open-air hot spring hot tub, minimalist Scandi furniture, a cozy wood stove, and absolute silence under the arctic skies.',
    country: 'Iceland',
    city: 'Selfoss',
    countryCode: 'IS',
    rating: 4.88,
    reviewsCount: 64,
    pricePerNight: 350,
    currency: 'EUR',
    guestsMax: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Wi-Fi', 'Geothermal Hot Tub', 'Fireplace', 'Parking', 'Kitchen', 'Coffee Machine', 'Glass Roof'],
    images: [
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1449034446853-66c86144b0ad?q=80&w=1200&auto=format&fit=crop',
    ],
    type: 'Cabin',
    category: 'mountain',
    isSuperHost: false,
    isVerified: true,
    isInstantBook: true,
    host: MOCK_HOSTS[3],
    latitude: 25,
    longitude: 20,
    featured: false,
    transactionMode: 'sell',
    salePrice: 1650000,
  },
  {
    id: 'prop-5',
    title: 'High-Line Penthouse & Panoramic Sky Deck',
    description: 'Perched in the sky overlooking New York City, this ultra-luxurious, modern 3-bedroom penthouse boasts private wrap-around terrace, custom marble bathrooms, sub-zero state-of-the-art chef kitchen, dedicated soundproof workspace with ultra fiber internet, and exclusive access to a resident rooftop lounge, wellness spa, and sky pool.',
    country: 'United States',
    city: 'New York',
    countryCode: 'US',
    rating: 4.91,
    reviewsCount: 112,
    pricePerNight: 550,
    currency: 'USD',
    guestsMax: 6,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ['Wi-Fi', 'Air Conditioning', 'Gym', 'Workspace', 'Rooftop Access', 'Doorman', 'Kitchen', 'Washing Machine'],
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
    ],
    type: 'Apartment',
    category: 'business',
    isSuperHost: true,
    isVerified: true,
    isInstantBook: true,
    host: MOCK_HOSTS[0],
    latitude: 35,
    longitude: 80,
    featured: false,
  },
  {
    id: 'prop-6',
    title: 'Whispering Pines A-Frame Forest Retreat',
    description: 'Disconnect and rejuvenate in this gorgeous architectural A-frame forest retreat surrounded by soaring pine woodlands. Designed with clean Scandi minimalism, the stay features a spacious outdoor cedar wood fire hot tub, a crackling internal wood stove, a cozy reading mezzanine overlooking the trees, and pet-friendly enclosed hiking paths starting from the backdoor.',
    country: 'Canada',
    city: 'Whistler',
    countryCode: 'CA',
    rating: 4.87,
    reviewsCount: 94,
    pricePerNight: 190,
    currency: 'USD',
    guestsMax: 4,
    bedrooms: 2,
    bathrooms: 1.5,
    amenities: ['Wi-Fi', 'Hot Tub', 'Fireplace', 'Parking', 'Kitchen', 'Pet Friendly', 'Hammock'],
    images: [
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop',
    ],
    type: 'Cabin',
    category: 'pet-friendly',
    isSuperHost: true,
    isVerified: false,
    isInstantBook: true,
    host: MOCK_HOSTS[3],
    latitude: 18,
    longitude: 40,
    featured: false,
  },
  {
    id: 'prop-7',
    title: 'Luxurious Oia Caldera Cliff Cave Suite',
    description: 'Carved straight into the volcanic caldera cliffs of Santorini, this exclusive luxury cave suite marries traditional Cycladic architecture with ultra-modern design. Wake up to breathtaking, uncompromised views of the Aegean sea, dive in your private heated plunge pool, and watch the legendary Santorini sunsets directly from your private white stone sunbed.',
    country: 'Greece',
    city: 'Santorini',
    countryCode: 'GR',
    rating: 4.97,
    reviewsCount: 154,
    pricePerNight: 490,
    currency: 'EUR',
    guestsMax: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Wi-Fi', 'Heated Plunge Pool', 'Air Conditioning', 'Breakfast Included', 'Terrace', 'Kitchenette'],
    images: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=1200&auto=format&fit=crop',
    ],
    type: 'Villa',
    category: 'luxury',
    isSuperHost: true,
    isVerified: true,
    isInstantBook: false,
    host: MOCK_HOSTS[1],
    latitude: 65,
    longitude: 75,
    featured: true,
  },
  {
    id: 'prop-8',
    title: 'The Eco-Glass Meadow Dome',
    description: 'An off-grid structural dome situated in a quiet, wildflower-filled meadow in Cornwall. Featuring a completely transparent dome canopy to gaze at shooting stars, a wood-fired sauna, chemical-free natural living materials, private farm-to-table breakfast basket delivered daily, and absolute serene isolation.',
    country: 'United Kingdom',
    city: 'Cornwall',
    countryCode: 'GB',
    rating: 4.92,
    reviewsCount: 42,
    pricePerNight: 210,
    currency: 'GBP',
    guestsMax: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Private Wood Sauna', 'Fireplace', 'Eco Toilet', 'Breakfast Included', 'Parking', 'Hammock'],
    images: [
      'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1200&auto=format&fit=crop',
    ],
    type: 'Tiny Home',
    category: 'countryside',
    isSuperHost: true,
    isVerified: true,
    isInstantBook: true,
    host: MOCK_HOSTS[0],
    latitude: 38,
    longitude: 25,
    featured: false,
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    userName: 'James Carter',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&auto=format&fit=crop',
    rating: 5,
    date: 'June 2026',
    comment: 'This was the most exceptional stay I have ever booked. The design details in the living room were spectacular. The host left a welcome hamper filled with local organic Cotswolds cheese and English sparkling wine. Truly breathtaking gardens!',
    breakdown: { cleanliness: 5, communication: 5, checkIn: 5, accuracy: 5, location: 5, value: 5 }
  },
  {
    id: 'rev-2',
    userName: 'Sophia Laurent',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop',
    rating: 4.8,
    date: 'May 2026',
    comment: 'The location is unbeatable. Extremely peaceful but easily accessible. High-speed internet is genuinely ultra-fast (fiber) which made remote conference calls smooth as butter. Would give 10 stars if possible.',
    breakdown: { cleanliness: 4.8, communication: 5, checkIn: 4.5, accuracy: 4.9, location: 5, value: 4.7 }
  },
  {
    id: 'rev-3',
    userName: 'Oliver Bennett',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop',
    rating: 5,
    date: 'April 2026',
    comment: 'Clean, beautifully appointed, and fully verified. It lived up to every aspect of the ProStates standard. Highly recommended for couples seeking an inspiring, silent retreat.',
    breakdown: { cleanliness: 5, communication: 5, checkIn: 5, accuracy: 5, location: 5, value: 5 }
  }
];

export const INITIAL_USER: UserProfile = {
  id: 'usr-1',
  name: 'Alexander Sterling',
  email: 'alex.sterling@prostates.com',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=150&auto=format&fit=crop',
  role: 'guest',
  joinedDate: 'December 2025',
  walletBalance: 1250.00,
  currency: 'GBP',
  language: 'en',
  phone: '+44 7700 900077',
  address: 'Belgravia, London, SW1W 9SZ, United Kingdom',
  bio: 'Product Designer and architecture enthusiast. Travel often for work and look for places that pair pristine remote-work spaces with authentic local visual design and premium materials.',
  preferences: {
    notificationsEmail: true,
    notificationsPush: true,
    marketingEmails: false,
    autoInstantBook: true,
  }
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    title: 'Booking Confirmed!',
    message: 'Your upcoming stay at The Stone Manor Estate starting 2026-08-12 is successfully confirmed by host Arthur Pendelton.',
    date: '2 hours ago',
    isRead: false,
    type: 'booking',
  },
  {
    id: 'notif-2',
    title: 'New Message from Clara',
    message: 'Hi Alexander, we would love to have you! We have pre-approved your instant booking request and verified your pet preferences.',
    date: '1 day ago',
    isRead: false,
    type: 'message',
  },
  {
    id: 'notif-3',
    title: 'Special Host Coupon Received',
    message: 'Enjoy 10% off your next booking at the Amalfi Cliffside Villa using coupon AMALFI10.',
    date: '3 days ago',
    isRead: true,
    type: 'offer',
  }
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk-1',
    propertyId: 'prop-1',
    propertyTitle: 'The Stone Manor Estate & Private Gardens',
    propertyCity: 'Cotswolds',
    propertyCountry: 'United Kingdom',
    propertyImage: 'https://images.unsplash.com/photo-1543872084-c7bd3822856f?q=80&w=200&auto=format&fit=crop',
    checkIn: '2026-08-12',
    checkOut: '2026-08-16',
    guestsCount: 4,
    totalPrice: 1800,
    status: 'upcoming',
    bookingDate: '2026-07-01',
  },
  {
    id: 'bk-2',
    propertyId: 'prop-3',
    propertyTitle: 'Kyoto Hanare Traditional Wooden Machiya',
    propertyCity: 'Kyoto',
    propertyCountry: 'Japan',
    propertyImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=200&auto=format&fit=crop',
    checkIn: '2026-04-10',
    checkOut: '2026-04-15',
    guestsCount: 2,
    totalPrice: 1400,
    status: 'completed',
    bookingDate: '2026-03-15',
  }
];

export const MOCK_CHAT_THREADS: ChatThread[] = [
  {
    id: 'chat-1',
    propertyId: 'prop-2',
    propertyTitle: 'Villa Bel-Air Cliffside & Infiniti Pool',
    propertyImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=150&auto=format&fit=crop',
    recipientName: 'Clara & Giovanni',
    recipientAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=150&auto=format&fit=crop',
    recipientRole: 'host',
    lastMessage: 'Hi Alexander, the private beach elevator will be fully operational during your stay in Positano!',
    lastMessageTime: '10:45 AM',
    unreadCount: 1,
    messages: [
      {
        id: 'msg-1',
        senderId: 'usr-1',
        senderName: 'Alexander Sterling',
        senderAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=150&auto=format&fit=crop',
        text: 'Hello Clara, I was wondering about the elevator to the private beach. Is it currently in service?',
        timestamp: '10:15 AM'
      },
      {
        id: 'msg-2',
        senderId: 'host-2',
        senderName: 'Clara & Giovanni',
        senderAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=150&auto=format&fit=crop',
        text: 'Hi Alexander, the private beach elevator will be fully operational during your stay in Positano!',
        timestamp: '10:45 AM'
      }
    ]
  },
  {
    id: 'chat-2',
    propertyId: 'prop-1',
    propertyTitle: 'The Stone Manor Estate & Private Gardens',
    propertyImage: 'https://images.unsplash.com/photo-1543872084-c7bd3822856f?q=80&w=150&auto=format&fit=crop',
    recipientName: 'Lord Arthur Pendelton',
    recipientAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&auto=format&fit=crop',
    recipientRole: 'host',
    lastMessage: 'We look forward to welcoming you to the Estate this August!',
    lastMessageTime: 'Yesterday',
    unreadCount: 0,
    messages: [
      {
        id: 'msg-3',
        senderId: 'usr-1',
        senderName: 'Alexander Sterling',
        senderAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=150&auto=format&fit=crop',
        text: 'Thank you for confirming the booking. Is the fireplace wood provided or should we arrange it?',
        timestamp: '2:15 PM'
      },
      {
        id: 'msg-4',
        senderId: 'host-1',
        senderName: 'Lord Arthur Pendelton',
        senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&auto=format&fit=crop',
        text: 'Wood is fully provided and stocked daily, complimentary of course. We look forward to welcoming you to the Estate this August!',
        timestamp: '3:00 PM'
      }
    ]
  }
];

export const MOCK_ORDERS: PurchaseOrder[] = [
  {
    id: 'ord-1',
    propertyId: 'prop-2',
    propertyTitle: 'Villa Bel-Air Cliffside & Infiniti Pool',
    propertyImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
    buyerName: 'Alexander Sterling',
    buyerEmail: 'alex.sterling@prostates.com',
    type: 'buy',
    totalPrice: 1250000,
    installmentsPaid: 0,
    installmentsTotal: 0,
    installmentAmount: 0,
    status: 'completed',
    orderDate: '2026-06-15',
  },
  {
    id: 'ord-2',
    propertyId: 'prop-3',
    propertyTitle: 'Scandinavian Fjords Off-Grid glass cabin',
    propertyImage: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?q=80&w=1200&auto=format&fit=crop',
    buyerName: 'Eleanor Vance',
    buyerEmail: 'eleanor.vance@gmail.com',
    type: 'installment',
    totalPrice: 850000,
    installmentsPaid: 5,
    installmentsTotal: 240,
    installmentAmount: 3800,
    status: 'active',
    orderDate: '2026-02-10',
  },
  {
    id: 'ord-3',
    propertyId: 'prop-4',
    propertyTitle: 'Manhattan Penthouse & Sky Terrace',
    propertyImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200&auto=format&fit=crop',
    buyerName: 'Marcus Aurelius',
    buyerEmail: 'marcus.capital@co.uk',
    type: 'sell',
    totalPrice: 1650000,
    installmentsPaid: 0,
    installmentsTotal: 0,
    installmentAmount: 0,
    status: 'pending',
    orderDate: '2026-07-02',
  },
  {
    id: 'ord-4',
    propertyId: 'prop-7',
    propertyTitle: 'Kyoto Machiya Bamboo sanctuary',
    propertyImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1200&auto=format&fit=crop',
    buyerName: 'Sora Takahashi',
    buyerEmail: 'sora.t@kyoto-stay.jp',
    type: 'installment',
    totalPrice: 520000,
    installmentsPaid: 12,
    installmentsTotal: 240,
    installmentAmount: 2200,
    status: 'active',
    orderDate: '2025-07-03',
  },
];

